config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    patch "account_update"
    patch "profile_update"
    get 'account'
    get 'profile'
  end
  devise_for :users
  root "home#index"
  resources :reservations, except: [:new]
  post "reservations/new"
  resources :rooms, except: [:edit, :update] do
    get "search", on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name,          presence: true, length: { maximum: 50 },
                            uniqueness: { case_sensitive: true }
  validates :description,   presence: true, length: { maximum: 1000 }
  has_many  :rooms,          dependent: :destroy
  has_many  :reservations,   dependent: :destroy
  has_many  :reserved_rooms, through:   :reservations, source: :room
  has_one_attached :icon_img
  attribute        :new_icon_img

  before_save do
    if new_icon_img
      self.icon_img = new_icon_img
    end
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [:account_update, :profile_update]

  def account
  end

  def profile
  end

  def account_update
    @user = User.find_by(id: params[:id])
    puts @user
    puts @user
    puts @user
    redirect_to users_profile_path
  end

  def profile_update
    @user = User.find_by(id: params[:id])
    if @user.update(user_params)
      redirect_to users_profile_path, notice: "プロフィール情報を更新しました"
    else
      render :profile
    end
  end

private
  def set_user
    @user = User.find(current_user.id)
  end

  def user_params
    params.require(:user).permit(
      :new_icon_img,
      :name,
      :email,
      :description,
      :password
    )
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/account.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc border-right border-right d-lg-block d-none">
      <ul>
        <li class="active"><%= link_to "アカウント", users_account_path %></li>
        <li class=""><%= link_to "プロフィール", users_profile_path %></li>
      </ul>
    </div>
    <div class="d-lg-none user-nav user-nav-mobile form-inline">
      <ul>
        <li class="active"><%= link_to "アカウント", users_account_path %></li>
        <li class=""><%= link_to "プロフィール", users_profile_path %></li>
      </ul>
    </div>
    <div class="col-lg-10">
      <div class="m-5 border">
        <div class="form-group border-bottom mx-1 p-3">
          <h5>アカウント</h5>
        </div>
        <div class="form-group form-row border-bottom mx-2 p-2">
          <label class="col-md-3" for="email">メールアドレス</label>
          <div class="col-md-9"><%= @user.email %></div>
        </div>
        <div class="form-group form-row border-bottom mx-2 p-2">
          <label class="col-md-3" for="password">パスワード</label>
          <div class="col-md-9">*********</div>
        </div>
        <div class="form-group">
          <%= link_to "編集", edit_user_registration_path, class: "col-md-2 btn btn-primary mx-3" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/profile.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2 user-nav user-nav-pc border-right d-lg-block d-none">
      <ul>
        <li class=""><%= link_to "アカウント", users_account_path %></li>
        <li class="active"><%= link_to "プロフィール", users_profile_path %></li>
      </ul>
    </div>
    <div class="d-lg-none user-nav user-nav-mobile form-inline">
      <ul>
        <li class=""><%= link_to "アカウント", users_account_path %></li>
        <li class="active"><%= link_to "プロフィール", users_profile_path %></li>
      </ul>
    </div>
    <div class="col-lg-10 user-view" style="background-color: #F6F8F9;">
      <div class="m-5 border" style="background-color: #fff;">
        <%= form_with model: @user, url: users_profile_update_path, local: true, method: :patch do |f| %>
        <%= render "devise/shared/error_messages", resource: resource %>

        <%= hidden_field_tag :id, @user.id %>
        <div class="form-group p-3 mx-2 border-bottom">
          <h5>プロフィール</h5>
        </div>
        <div class="form-group form-row p-3 mx-2 border-bottom">
          <div class="col-md-3 required-b pt-2">
            <%= f.label :new_icon_img %>
            <span class="badge badge-danger p-1">必須</span>
          </div>
          <div id="icon-img" class="col-md-9 text-center mb-4">
            <%= image_tag "/default_profile_img.jpg",
                  class: "rounded-circle text-center", size: "65x65",
                  id: "fileInputButton", onclick: "document.getElementById('fileInput').click()" %>
            <%= f.file_field :new_icon_img, autofocus: true, autocomplete: "name", id: "fileInput",
                    style: "display:none", "v-on:change": "btnClick" %>
          </div>
        </div>
        <div class="form-group form-row p-3 mx-2 border-bottom">
          <div class="col-md-3 required-b pt-2">
            <%= f.label :name %>
            <span class="badge badge-danger p-1">必須</span>
          </div>
          <%= f.text_field :name, autofocus: true, autocomplete: "name",
                  class: "form-control col-md-9 px-2 mb-4", placeholder: "" %>
          <% if resource.errors.include?(:name) %>
            <p class="pt-1" style="color: red;"><%= "※ #{resource.errors.full_messages_for(:name).first}" %>
          <% end %>
        </div>

        <div class="form-group form-row p-3 mx-2 border-bottom">
          <div class="col-md-3 required-b pt-2">
            <%= f.label :description %>
            <span class="badge badge-danger p-1">必須</span>
          </div>
          <%= f.text_field :description, autofocus: true, autocomplete: "description",
                  style: "height: 150px;", class: "form-control col-md-9 px-2 mb-4", placeholder: "自己紹介を入力" %>
          <% if resource.errors.include?(:description) %>
            <p class="pt-1" style="color: red;"><%= "※ #{resource.errors.full_messages_for(:description).first}" %>
          <% end %>
        </div>

        <div class="actions pb-3 p-3 mx-2">
          <%= f.submit "更新", class: "col-2 btn btn-primary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'icon_img_attach' %>