config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    patch "account_update"
    patch "profile_update"
    get 'account'
    get 'profile'
  end
  devise_for :users
  root "home#index"
  resources :reservations, except: [:new]
  post "reservations/new"
  resources :rooms, except: [:edit, :update] do
    get "search", on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="container h-100 d-flex align-items-center justify-content-center">
    <p>© 2020 POTEPAN.INC.</p>
</div>

app/views/shared/_header.html.erb
<div class="header-wrapper">
    <div class="float-left form-inline">
        <%= link_to image_tag("/logo.png", class: "logo-img h-100"), "/" %>
        <%= form_for :rooms_search ,url: search_rooms_path, method: :get do |form| %>
            <div class="header-sharch d-lg-inline-block d-none">
                <i class="fas fa-map-marker-alt" style="margin-top: 12px; margin-left: 5px; position:absolute;"></i>
                <%= form.text_field :area, value: "", class: "form-control pl-4", placeholder: "エリア" %>
            </div>
            <div class="header-sharch d-lg-inline-block d-none">
                <i class="fas fa-search" style="margin-top: 12px; margin-left: 5px; position:absolute;"></i>
                <%= form.text_field :keyword, value: "", class: "form-control pl-4", placeholder: "キーワード" %>
            </div>
            <%= form.submit "", class: "d-none" %>
        <% end %>
    </div>
    <div class="float-right mr-2">
        <% if current_user.nil? %>
            <div class="mt-3">
                <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary mr-3" %>
                <%= link_to "登録する", new_user_registration_path, class: "btn btn-secondary" %>
            </div>
        <% else %>
            <div class="nav-item d-sm-inline-block d-none mr-3 text-light">
                <%= current_user.name %>
            </div>
            <div class="btn-group mr-3">
                <div class="pt-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" data-offset="0,5">
                  <% if current_user.icon_img.attached? %>
                    <%= image_tag current_user.icon_img, class: "rounded-circle", size: "57x57" %>
                  <% else %>
                    <%= image_tag "/default_profile_img.jpg", class: "rounded-circle", size: "57x57" %>
                  <% end %>
                </div>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><%= link_to "登録済みルーム一覧", rooms_path, class: "dropdown-item" %></li>
                    <li><%= link_to "予約済みルーム一覧", reservations_path, class: "dropdown-item" %></li>
                    <li><%= link_to 'ルーム登録', new_room_path, class: "dropdown-item" %></li>
                    <li><%= link_to "設定", users_account_path, class: "dropdown-item" %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, class: "dropdown-item", method: :delete %></li>
                </ul>
            </div>
        <% end %>
    </div>
</div>