config/routes.rb
Rails.application.routes.draw do
  namespace :users do
    patch "account_update"
    patch "profile_update"
    get 'account'
    get 'profile'
  end
  devise_for :users
  root "home#index"
  resources :reservations, except: [:new]
  post "reservations/new"
  resources :rooms, except: [:edit, :update] do
    get "search", on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
   belongs_to :maker, class_name: "User", foreign_key: "user_id"
   has_many   :reservations, dependent: :destroy
   has_many   :appointers,   through: :reservations, source: :user

   validates  :name,        presence: true
  # validates  :new_room_img, presence: true
   validates  :description, presence: true
   validates  :price,       presence: true
   validates  :address,     presence: true

   has_one_attached :room_img
   attribute        :new_room_img

   before_save do
     if new_room_img
       self.room_img = new_room_img
     end
   end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, except: [:search, :show]
  before_action :set_room, only: [:show, :update, :destroy]


  def search
    @rooms = Room.where("address LIKE ? AND description LIKE ?",
                "%#{params[:rooms_search][:area]}%", "%#{params[:rooms_search][:keyword]}%")

    @rooms = Room.all if params[:rooms_search][:area] == nil && params[:rooms_search][:keyword] == nil
  end

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = current_user.rooms.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @reservation = Reservation.new
    @reservation.room = @room
    @reservation.user = current_user
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)
    @room.maker = current_user

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: '部屋が登録されました。' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: '部屋が更新されました。' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:user_id, :new_room_img, :name, :description, :price, :address)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class="container-fluid px-5 py-4">
  <p id="notice"><%= notice %></p>
  <h4 class="pb-4">登録済みルーム一覧</h4>

  <% if @rooms.present? %>
    <table class="table table-striped" style="width: 100%;table-layout:fixed;word-break: break-all;word-wrap: break-all;">
      <thead>
        <tr>
          <th scope="col">ルーム画像</th>
          <th scope="col">ルーム名</th>
          <th scope="col">ルーム紹介</th>
          <th scope="col">料金</th>
          <th scope="col">作成日</th>
          <th scope="col">削除</th>
        </tr>
      </thead>
      <tbody>
        <% @rooms.each do |room| %>
          <tr class="border-bottom">
            <td>
              <% if room.room_img.attached? %>
                <%= link_to image_tag(room.room_img, class: "w-100 h100", style: "max-width: 240px; max-height: 140px;"), room %>
              <% else %>
                <%= link_to image_tag("/room_img.jpg", class: "w-100 h100", style: "max-width: 240px; max-height: 140px;"), room %>
              <% end %>
            </td>
            <td><%= link_to room.name, room %></td>
            <td><%= room.description %></td>
            <td><%= "¥#{room.price}" %></td>
            <td><%= room.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>登録されている部屋はございません</p>
  <% end %>
</div>

app/views/rooms/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-2 room-nav room-nav-pc border-right d-lg-block d-none">
      <ul>
        <li class="active">基本情報</li>
      </ul>
    </div>
    <div class="col-lg-2 room-nav room-nav-mobile d-lg-none">
      <ul>
        <li class="active">基本情報</li>
      </ul>
    </div>
    <div class="col-lg-10" style="background-color: #F6F8F9;">
      <div class="m-5 border" style="background-color: #fff;">
        <%= form_with(model: @room, local: true) do |form| %>
          <div class="form-group p-3 mx-2 border-bottom">
            <h5>ルーム情報登録</h5>
          </div>
          <div class="field form-group form-row p-3 mx-2 border-bottom">
              <div class="col-md-3 required-b pt-2">
                  <%= form.label :name %>
                  <span class="badge  badge-danger p-1">必須</span>
              </div>
              <%= form.text_field :name, autofocus: true, autocomplete: "name", class: "form-control col-md-9 px-2 mb-4" %>
              <br />
              <% if @room.errors.include?(:name) %>
                <p style="color: red;"><%= "※ #{@room.errors.full_messages_for(:name).first}" %>
              <% end %>
          </div>

          <div class="field form-group form-row p-3 mx-2 border-bottom">
              <div class="col-md-3 required-b pt-2">
                  <%= form.label :description %>
                  <span class="badge  badge-danger p-1">必須</span>
              </div>
              <%= form.text_field :description, autofocus: true, autocomplete: "description", class: "form-control col-md-9 px-2 mb-4",
                    style: "height: 200px;"%>
              <% if @room.errors.include?(:description) %>
                <p style="color: red;"><%= "※ #{@room.errors.full_messages_for(:description).first}" %>
              <% end %>
          </div>

          <div class="field form-group form-row p-3 mx-2 border-bottom">
              <div class="col-md-3 required-b pt-2">
                  <%= form.label :price %>
                  <span class="badge  badge-danger p-1">必須</span>
              </div>
              <%= form.text_field :price, autofocus: true, autocomplete: "price", class: "form-control col-md-9 px-2 mb-4" %>
              <% if @room.errors.include?(:price) %>
                <p style="color: red;"><%= "※ #{@room.errors.full_messages_for(:price).first}" %>
              <% end %>
          </div>

          <div class="field form-group form-row p-3 mx-2 border-bottom">
              <div class="col-md-3 required-b pt-2">
                  <%= form.label :address %>
                  <span class="badge badge-danger p-1">必須</span>
              </div>
              <%= form.text_field :address, autofocus: true, autocomplete: "address", class: "form-control col-md-9 px-2 mb-4" %>
              <% if @room.errors.include?(:address) %>
                <p style="color: red;"><%= "※ #{@room.errors.full_messages_for(:address).first}" %>
              <% end %>
          </div>

          <div class="field form-group form-row p-3 mx-2 border-bottom">
              <div class="col-md-3 required-b pt-2">
                  <%= form.label :new_room_img %>
                  <span class="badge badge-danger p-1">必須</span>
              </div>
              <div>
                <%= form.file_field :new_room_img, autofocus: true, autocomplete: "new_room_img", class: "form-control col-md-9 px-2 mb-4" %>
                <% if @room.errors.include?(:new_room_img) %>
                  <p style="color: red;"><%= "※ #{@room.errors.full_messages_for(:new_room_img).first}" %>
                <% end %>
              </div>
          </div>

          <div class="actions p-3 mx-2">
            <%= form.submit "登録", class: "col-2 btn btn-primary mx-3" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<%= javascript_pack_tag 'room_img_attach' %>

app/views/rooms/search.html.erb
<div class="container mb-5">
  <h4 class="pb-4"><%= "検索結果：#{@rooms.count}件" %></h4>
  <div class="row">
    <% if @rooms.present? %>
      <% @rooms.each do |room| %>
        <div class="col-sm-6 col-lg-4 col-xl-3">
          <div class="room-content-wrapper">
            <%= link_to room do %>
              <div class="card border-none" style="border-radius: 0px;">
                <div class="card-header" height="20"></div>
                  <% if room.room_img.attached? %>
                    <%= image_tag room.room_img, height: "180", class: "w-100 bd-placeholder-img card-img-top" %>
                  <% else %>
                    <%= image_tag "/room_img.jpg", height: "180", class: "w-100 bd-placeholder-img card-img-top" %>
                  <% end %>
                <div class="card-body">
                  <h5 class="float-left w-100 text-black-50"><%= room.description %></h5>
                  <p class="float-left w-100 text-dark"><%= room.address %></p>
                  <p class="float-right text-dark"><%= "¥ #{room.price}" %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p>検索データがありません</p>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="container py-4">
  <div class="row">
    <div class="col-md-8 card border-0">
      <div class="card-body pt-0">
        <% if @room.room_img.attached? %>
          <%= image_tag @room&.room_img, class: "bd-placeholder-img card-img-top", style: "border-radius: 0px;" %>
        <% else %>
          <%= image_tag "/room_img.jpg", class: "bd-placeholder-img card-img-top", style: "border-radius: 0px;" %>
        <% end %>
        <div class="row no-gutters">
          <div class="col-2 d-flex align-items-center justify-content-center">
            <%= image_tag "/default_profile_img.jpg", class: "rounded-circle", size: "57x57" %>
          </div>
          <div class="col-10">
            <div class="card-body">
              <p class="card-text" style="font-size: 18px; font-weight: bold;"><%= @room.name %></p>
              <p class="card-text"><%= @room.address %></p>
            </div>
          </div>
          <div class="card-body border-top border-bottom">
            <p class="card-text"><%= @room.description %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="rounded border p-4">
        <p>
          <%= "¥ #{@room.price}／日" %>
        </p>
        <%= form_with(model: @reservation, url: reservations_new_path, local: true, method: :post, class: "py-3") do |form| %>
          <%= form.hidden_field :user_id, value: current_user.id %>
          <%= form.hidden_field :room_id, value: @room.id %>
          <div class="field form-group">
            <%= form.label :start_date %>
            <%= form.date_field :start_date, class: "form-control" %>
            <% if @reservation.errors.include?(:start_date) %>
              <p style="color: red;"><%= "※ #{@reservation.errors.full_messages_for(:start_date).first}" %>
            <% end %>
          </div>

          <div class="field form-group">
            <%= form.label :end_date %>
            <%= form.date_field :end_date, class: "form-control" %>
            <% if @reservation.errors.include?(:end_date) %>
              <p style="color: red;"><%= "※ #{@reservation.errors.full_messages_for(:end_date).first}" %>
            <% end %>
          </div>

          <div class="field form-group">
            <%= form.label :number_of_people %>
            <%= form.number_field :number_of_people, class: "form-control" %>
            <% if @reservation.errors.include?(:number_of_people) %>
              <p style="color: red;"><%= "※ #{@reservation.errors.full_messages_for(:number_of_people).first}" %>
            <% end %>
          </div>

          <div class="actions form-group">
            <% if current_user %>
              <%= form.submit "予約する", class: "btn btn-primary mr-3 form-control"  %>
            <% else %>
              <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary mr-3 form-control" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>